name: Frontend CI

on:
  pull_request:
    branches:
      - master
    paths:
      - 'starter/frontend/**'

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

  test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: CI=true npm test -- --watchAll=false

  build:
    runs-on: ubuntu-latest

    needs:
      - lint
      - test

    defaults:
      run:
        working-directory: starter/frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: starter/frontend/.nvmrc
          cache: npm
          cache-dependency-path: starter/frontend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
# ASIA5CSHSB5HMSUYX5D4
# /PnMjOnElcgOsikSlQSh/gLuKsK2oN9SEga2S3fH
# IQoJb3JpZ2luX2VjELL//////////wEaCXVzLXdlc3QtMiJGMEQCIHHa1te9DRqWU9OuMTntSSDE3NB5VTrP7+4Wniz+QLKAAiBfCcTc0TLVk1BjkpBk24bcFWxuY4PJIIDJvqQUCZuUMSq+Agh7EAIaDDg5ODg3MTk4ODA0NiIMgYwTm0TmkMsWhtpEKpsCxN4BRLi6CXROUn6P2z6SF6GNYDzMadQE0nNjw8g1LG7kqpKoCiw8WxMbzrnLDqkUusg8NUSgis+GREO4mjwZt9aLwl+gN5PBCGxOSvB4xODRJCMENVXorNyz+veWQn88WQi/qQHr2rN1ncvmHxv1lXvMMEVPw4azdOMUGujES+PqJsN4RLnGZo6og8DOH+pJcl71BNi9x2vVwjWTqU+uAtm4g7dVuOrpOgbNGiriv1ialzB2IUOa42Ux4VBtumnX7mFvyEfIoLfSy1v6SuzQTHEi/dWaBbUuBuvYjgrYS3uGSVcvpwzd/ZFNka1vuyvuvudH7jVxWh0pjw3ZNm0siZj9J/Ju99pvYjRCQqOjGh0F8MCg5dFrCns1kzDK0fjVBjqeAY/tyFTN6+wXr1Gg/3TVXpKhpGiGZJxYE7shUMuKxtsFKWyCN6WnJ6P4uHQ3WqIpL+G2THcEAPEEQ/Sk+e6OwSZE4i84XgD0LEy7mHB7QQYvN4ob2oj+J4zb8tk0egOIJVhWC6cE2HUkOFxoFe4kHEOZ+xN8QhXODRdaPCLFvWWAnwIgra5yPq4bbfuFPfpIADKK01zs/rMiaN+d7Y5E

